version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  my-db:
    image: mysql:8.0
    container_name: my-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword" ]
      interval: 30s
      timeout: 10s
      retries: 5

  management-app:
    image: management-app
    container_name: management-app
    build:
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    depends_on:
      my-db:
        condition: service_healthy
    networks:
      - my-network


